// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWlNE_L4tYZKTtyOocmb5XgbHNLb1iktM',
    appId: '1:579204936860:web:2c7923deef8005d27de959',
    messagingSenderId: '579204936860',
    projectId: 'api-app-11ed8',
    authDomain: 'api-app-11ed8.firebaseapp.com',
    storageBucket: 'api-app-11ed8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRcH6B-toyJz5FRGSgRM2Qq4QYYMEmbZM',
    appId: '1:579204936860:android:71d0f00d04717bb77de959',
    messagingSenderId: '579204936860',
    projectId: 'api-app-11ed8',
    storageBucket: 'api-app-11ed8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeHaskYov-EvfXW_bCNK958rp34qMLUOo',
    appId: '1:579204936860:ios:25b677f64c344f857de959',
    messagingSenderId: '579204936860',
    projectId: 'api-app-11ed8',
    storageBucket: 'api-app-11ed8.appspot.com',
    iosClientId: '579204936860-06j90dg83s0h5574r5b6rq08uhkj4q9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.apiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeHaskYov-EvfXW_bCNK958rp34qMLUOo',
    appId: '1:579204936860:ios:25b677f64c344f857de959',
    messagingSenderId: '579204936860',
    projectId: 'api-app-11ed8',
    storageBucket: 'api-app-11ed8.appspot.com',
    iosClientId: '579204936860-06j90dg83s0h5574r5b6rq08uhkj4q9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.apiApp',
  );
}
